### ISSUE TITLE
Création d'un deuxième remote

### ISSUE THREAD

**Issue by ssydney77** [ssydney77/ProjetGit-TemplatePortfolio#11]
## Description de la fonctionnalité

Avoir un nouveau remote pour que chaque collaborateurs puisse bénéficier de son propre remote 

## Contexte

C'est une bonne pratique dans la structure de projet

## Proposition de solution

Créer un nouveau remote via le terminal et le pusher sur le projet

## Comportement attendu

Avoir un deuxieme remote en plus de origin

## Captures d'écran

X

## Informations supplémentaires

X

**Comment by Jobela94** [comment]
J'ai crée mon second remote !
